### ISSUE TITLE
Support importing into TypeScript projects

### ISSUE THREAD

**Issue by amylo** [pyrsmk/qwest#136]
I'm using Qwest 4.4.5 in a TypeScript project.
It would be to be able to do the following:
```
import qwest from 'qwest';
// OR...
import {qwest} from 'qwest';
```

The above gives me the following error when I transpile the TypeScript:
```
TS7016: Could not find a declaration file for module 'qwest'. '.../node_modules/qwest/src/qwest.js' implicitly has an 'any' type.
```

So far the workaround is a gross use of `require()` manually specifying the path:
```
import qwest = require('..../node_modules/qwest/qwest.min');
```

**Comment by pyrsmk** [comment]
Mmmmh... I don't really know TypeScript, but it seems the issue comes from the UMD bundling by Browserify. Anyway, it's great that you have a workaround because I don't fix bugs anymore for the `4.4` version, unless it's necessary, because I've planned to completely rewrite qwest in ES6 for the upcoming v5. When, the v5 is out I'll come back to you to see if all is working as expected ;)

**Comment by skyline94** [comment]
@amylo im using typescript, you can import qwest like this:
`import * as qwest from 'qwest'`
works as expected.

**Comment by pyrsmk** [comment]
:+1:

**Comment by amylo** [comment]
Thanks!
`import * as qwest from 'qwest'` works well.
