### ISSUE TITLE
Promises: then should accept two arguments

### ISSUE THREAD

**Issue by mroderick** [pyrsmk/qwest#27]
For Promises/A+ compliance, `then` should accept two arguments. See https://promisesaplus.com/#point-22

@pyrsmk Would you consider replacing the promises implementation with https://github.com/timjansen/pinkyswear.js or similar compliant implementation?

**Comment by pyrsmk** [comment]
With that implementation I should drop the `catch` promise in favor of having two arguments in the `then` promise. I can't do that until the next major release. And since it's just a matter of design and that it does not add any behavior to the library, it shouldn't be harmful. Anyway, it's a good idea to implement a better promises implementation, I'll probably pick pinkyswear.js for that.

Thanks for the recommendation ;)

**Comment by mroderick** [comment]
There's also the option of going with ES6 Promises via https://github.com/jakearchibald/es6-promise, but that seems a bit more intrusive as it creates a global `Promise`. To me this makes it a bit unappealing to library authors. Choices, choices, choices.

**Comment by pyrsmk** [comment]
And pikyswear is tinier (0.8ko vs 5.16ko) and better documented.

**Comment by danielr-minted** [comment]
You don't need to drop catch.  Catch is just then(undefined, resolve), and is easily incorporated into pinkySwear.  The constructor takes an "extend" function of a single argument that can append functions to the object in pinkyswear.
Assuming I'm reading the source correctly:
<code>
var proto = pinkySwear(function(set) { set['catch'] = function (f) { return set['then'](undefined, f) }; return set } );
</code>

**Comment by pyrsmk** [comment]
But... Why keeping `catch()` if `then()` directly supports it and is compliant?

In fact, I don't like the idea to have two functions for the `then()` method. It's less readable, less pretty. But we should follow specs to have an uniformized way of using promises.

Supporting pinkyswear as a dependency for promises is not really a problem, and we'll have better stability.

My problem is with the design behind the Promises/A+ spec and how I should implement it in qwest. I'll take any advice or idea, because I'm a bit lost ;)

**Comment by danielr-minted** [comment]
It's sugar.  Then with two arguments is nicer for library implementors that want to write code for composing and combining promises.  catch() makes the intent of the user of the promise a little clearer.  Also catch is very likely to be in the next version of javascript (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.prototype.catch) and is already directly supported by Chrome, Firefox, Safari,   Firefox is described here: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise.

**Comment by pyrsmk** [comment]
Thanks for your clarifications! So I will implement it that way. It could take some time. Maybe this week, maybe the next.

**Comment by pyrsmk** [comment]
Since this issue is part of #51, I close it.
