### ISSUE TITLE
Make promises chainable

### ISSUE THREAD

**Issue by togakangaroo** [pyrsmk/qwest#57]
Maybe I'm wrong in understanding promises but it is my understanding that a promise returned from `then` should be chainable. For example you would expect the following

	let r = qwest.post('/api/ProspectiveCustomer')
				.then(function(){ return this.getResponseHeader('Location')  })
				.then((url) => qwest.get(url) )
				.then((d) => console.log("this should be json", d))

to work, but it doesn't! Seems like the second `then` chains the returned promise into the the next parameter. Instead it's supposed to return a new promise that resolves when everything is done.

That's the way every other promise library I've used has worked at least...

**Comment by pyrsmk** [comment]
I don't really understand your code :p I don't know what the syntax `(url) => qwest.get(url)` should do. Anyway, it should chain promises as you're saying.

I think the problem comes from the call for qwest inside qwest itself. Try to externalize your `qwest.get(url)` call. I've planned to remove the current promises implementation for a better/stronger/external library.

**Comment by togakangaroo** [comment]
Thanks...that syntax is es6 arrow functions :) It's already deployed in Firefox and looks like its [getting close in Chrome](https://code.google.com/p/v8/issues/detail?id=2700)

**Comment by pyrsmk** [comment]
Saw that :p I read some ES6 specs but it's quite obscure for some things to me ^^

Anyway, did the externalization of your qwest calls work?

**Comment by togakangaroo** [comment]
Unfortunately I switched away from qwest to full jquery when I hit this as
I use promise chaining a lot. I can see about checking out the code and
maybe making a pr in a few days

**Comment by pyrsmk** [comment]
I completely understand your choice ;) I had to do the same with some promising libraries : our clients can't wait :p 

Otherwise, don't waste your time on this. I've planned to use an [external library](https://github.com/timjansen/pinkyswear.js) to have a valid and compliant promises spec into qwest. In all cases, thanks for your help!

**Comment by pyrsmk** [comment]
Since this issue is part of #51, I close it.

**Comment by pyrsmk** [comment]
Seems completely related to #22 
That previous issue should have be rejected instead of fixed because that behavior is not standard at all. It will be fixed by the next release.
