### ISSUE TITLE
options.responseType auto issue

### ISSUE THREAD

**Issue by petewailes** [pyrsmk/qwest#62]
Chrome appears to throw a warning for xhr.responseType set as auto. This makes sense, as the valid values are:

* blank || text (blank is the default, and both set as DOMString)
* arraybuffer
* blob
* document
* json

I'd guess that for most people, json would be a sensible default, but in either case it should really be a required field.

I'd suggest having it either as a required option, or having it pass in as an argument.

For reference, am using 1.6.0 on Chrome 43.0.2357.81 m 64-bit

**Comment by pyrsmk** [comment]
It's a bug. And it should be corrected by now. Update your package and tell me if it's working ;)

In fact, the `auto` mode is here to avoid to set the `responseType` for the common mime types. If your server returns a valid `Content-Type` header then qwest will detect json, xml and fallbacks to plain text otherwise.

**Comment by nigel-sirisomphone** [comment]
I've also been experiencing this issue. My quick fix was to change the default settings:
`options.responseType='responseType' in options?options.responseType.toLowerCase():'json';`

After reading this, I updated the npm package, and confirm it's working :+1:

**Comment by pyrsmk** [comment]
Great! Thanks for all your help ;)
