### ISSUE TITLE
Support for Babel ES6 modules.

### ISSUE THREAD

**Issue by singerxt** [pyrsmk/qwest#63]
Hello ! 

Thank you for all your hard work on qwest ! ;-)
I tried to use your library with Babel compiler but unfortunately when I'm trying import your library I'm getting ```undefined```

use case

```javascript

import {qwest} from './vendor/qwest.js'

class test {
  constructor () {
    console.log(qwest); //undefined
  }
}
```

Thanks!

**Comment by pyrsmk** [comment]
Hi, thanks for the interest you're giving to qwest ;)

Is ES6 supporting AMD/CommonJS modules? Or only ES6 modules?

**Comment by singerxt** [comment]
Hello ! My Babel configuration is set to CommonJS - compiled code looks 

```
var qwest = require("../vendor/qwest.js").qwest;
```

**Comment by singerxt** [comment]
Oh I see 
```
var qwest = require("../vendor/qwest.js");
```
Did a job ;-) I'll try to fix this and if this bug is not Babel configuration I'll prepare PR. Thanks!

**Comment by pyrsmk** [comment]
Ahah yes, it requires directly qwest. Maybe it's an incompatibility on how modules are required between ES6 and CommonJS?

For ES6, I had open a ticket for that but since I have not much time to understand the whole ES6 thing and there's a big lack of documentation about it, I closed the ticket.

But I would be happy to switch qwest to ES6. It was planned for the 2.0 release. I think I could reopen #51

**Comment by singerxt** [comment]
Sure Thing! 

Feel free to assign ticket to me ;-) I'll prepare new branch with es6 compiler (Babel + Gulp) and I'll start working on that.

Thanks!

**Comment by pyrsmk** [comment]
Ok, I'm preparing all of that, thanks a lot for your help ;)

**Comment by pyrsmk** [comment]
(please reopen if needed and let me know how's goind the babel ticket ^^)
