### ISSUE TITLE
Webpack prefers sources

### ISSUE THREAD

**Issue by mr-wildcard** [pyrsmk/qwest#80]
Hi,

What do you think about targeting `src/qwest.js` file in `package.json` as main entry as well as you did for bower.json ?

**Comment by pyrsmk** [comment]
Yeah, it should be better ;)

**Comment by pyrsmk** [comment]
In fact, I chose to target the built file because of browserify, per example. In a configuration where we load all dependencies automatically via `package.json`, the library couldn't run without its dependencies.

**Comment by pierot** [comment]
Are you planning to release this as an update?

**Comment by pyrsmk** [comment]
Is this blocking development under NPM or something?

**Comment by pierot** [comment]
@pyrsmk not blocking but it keeps throwing warnings .. https://www.dropbox.com/s/q35j4mrv7w4uhjf/Screenshot%202015-10-09%2020.03.16.png?dl=0

**Comment by pyrsmk** [comment]
I planned to add derequire into the gulpfile. It should do the trick?

**Comment by pierot** [comment]
As far as I can see you need to provide a non-minified version in the root and reference it as 'main' in the package.json.

**Comment by pyrsmk** [comment]
A non-minified version at the root of the project? Why?

**Comment by pierot** [comment]
Basically, what Webpack is saying, don't use minified versions of a library. Because otherwise Webpack and whatever plugin you use, can't fully process the library into whatever minification or `uglification` flow.

I think you should provide a minified version, but by default you should let the use be in control. Therefor: point to the non-minified version in the package.json.

As an example: this is a full list of all the options you can choose when uglifying with Ugliy-js: https://github.com/mishoo/UglifyJS2.

**Comment by pyrsmk** [comment]
Ok, so I'll update this with the next release. Probably this week end ;)

**Comment by pierot** [comment]
Thanks! Love the library by the way, great work :)

**Comment by pyrsmk** [comment]
Thanks :)

**Comment by pyrsmk** [comment]
Updated!

**Comment by pierot** [comment]
Just a reminder: could you push 2.2.0 to npmjs? Thanks :)

**Comment by pyrsmk** [comment]
That's the not the case ?_?

**Comment by pyrsmk** [comment]
Grmblblbl

**Comment by pyrsmk** [comment]
Fixed ^^

**Comment by pierot** [comment]
:+1:
