### ISSUE TITLE
Something wrong in documents?

### ISSUE THREAD

**Issue by hulufei** [pyrsmk/qwest#98]
Here is the document about `catch` and `complete`

```
     .catch(function(xhr, response, e) {
        // Process the error
     })
     .complete(function(xhr, response) {
        // Always run
     });
```

In fact, I got the params like this: `.catch(function(error))` and `.complete(function(response))`

**Comment by hulufei** [comment]
Oh, I used `.then` before `.catch` and `.complete` like:

```
qwest.get(...)
  .then(function(xhr, res) { return res; })
  .catch(function(err) { console.log('only error params'); })
  .complete(function(res) { console.log('only response without xhr'); });
```

I'm still a little confused through

- How `.complete` got two params, AFAIK, promise can't return multi values.
- `.catch` should always got a single `error` params?

**Comment by pyrsmk** [comment]
Just to be sure, what version of qwest are you using? Because `catch()` and `then()` don't return these params since a long time.

In fact, with PinkySwear (which is the promises dependency of qwest) I can pass several parameters without any problem.

For `complete()`, I'm considering to remove that function in the far future because it's not really useful, and its parameters are ambiguous. Because if a `catch` si triggered then the error parameters will be pass, and if a `then` is triggered that will be the success parameters.

For `catch()`, we need to have several values because `catch` is not just an error. You may want to verify the response body from the server, the HTTP status, etc...

**Comment by hulufei** [comment]
I'm using 2.2.6

I finally figured out PinkySwear is just another promise implementation, passing more than one value is an extension, and I mixed it up with ES6 Promise.

For `complete()`, thanks for clarifying, I got it now.

For `catch()`, you mean it should always got `(xhr, error)` params?

**Comment by pyrsmk** [comment]
It always have `(xhr, response, error)` params, because they're all useful, yes ;)

For your bug with `catch` and `complete`, can you add `console.log(arguments)` inside your promises, just to be sure?

**Comment by hulufei** [comment]
Alright, I put a simple demo in jsfiddle:

https://jsfiddle.net/hulufei/cg939dr0/

Hope this helpful.

**Comment by pyrsmk** [comment]
Ah! The params are invalid in the second call (and the complete function). Thanks for the fiddle, I'll take a look at this.

**Comment by pyrsmk** [comment]
I think the problem comes from the promises implementation. My mistake here is I don't understand promises well in depth.

If I'm right, promises won't chain. The first then and the first catch are for the request resolution. But others promises are dependent of the previous promise resolution. To be clear, the second `then` is for the first `then` resolution. That's why `complete` doesn't work either because of the previous promises.

**Comment by hulufei** [comment]
Yeah, it's inconsistent with chained promises, that's why i'm confused with the doc.

Any idea to improve this? Maybe change to ES6 Promise like https://github.com/github/fetch did:)

**Comment by pyrsmk** [comment]
I think PinkySwear already works like this. You need to return a value in the first then to have it in the second too, like `fetch`. See https://jsfiddle.net/cg939dr0/3/

**Comment by pyrsmk** [comment]
As it seems there's no bug here, I close this ticket. Reopen it if needed ;)
